//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volta_Projeto_Taskool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Usuario1 { get; set; }
        public string Telefone { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
    }
}
